### PR TITLE
Add kitchen-openstack

### PR DESCRIPTION
**Pull request by ramereth**
As a Chef user who interacts with an OpenStack cluster with test-kitchen, I want
to be able to use Chef Workstation with OpenStack.

This only pulls in the following additional gem dependencies:

- fog-core
- fog-json
- fog-openstack

Signed-off-by: Lance Albertson <lance@osuosl.org>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tyler-ball** [comment]
We had [previously](https://github.com/chef/chef-dk/commit/c0f8abb1f3497c0e6af93b62fef85a93fc816d1a) removed fog dependencies from our Workstation (previously DK) install to keep the size smaller. It also looks like kitchen-openstack is 'unmaintained' per its [status](https://github.com/test-kitchen/kitchen-openstack#status), but it did get a release recently to make it more compatible with the Workstation install.

If you `chef gem install kitchen-openstack` does that install correctly and allow you to use the driver? Or does it refuse to load it?

**Comment by ramereth** [comment]
> We had [previously](https://github.com/chef/chef-dk/commit/c0f8abb1f3497c0e6af93b62fef85a93fc816d1a) removed fog dependencies from our Workstation (previously DK) install to keep the size smaller. It also looks like kitchen-openstack is 'unmaintained' per its [status](https://github.com/test-kitchen/kitchen-openstack#status), but it did get a release recently to make it more compatible with the Workstation install.

I'm very interested in becoming the new maintainer. Let me reach out to the test-kitchen folks to see what I need to do.

> If you `chef gem install kitchen-openstack` does that install correctly and allow you to use the driver? Or does it refuse to load it?

I'm pretty sure it works this way, but I was hoping to reduce the need of initial setup for our environment and would be useful for other potential users.

It looks like previously DK included many more fog gems, but this only includes a total of 4 new gems to workstation.

As far as size goes, here's what I see:
```
416K    /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/fog-core-2.2.0
28K     /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/fog-json-1.2.0
5.0M    /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/fog-openstack-1.0.10
44K     /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/kitchen-openstack-5.0.0
5.5M    total
```
I was a bit surprised at how large fog-openstack pulls in, but I imagine most of those files compress well. I'm not sure if that goes beyond your threshold though.

Thanks for your consideration!

**Comment by tas50** [comment]
FYI: In the past we purposefully did not include these gems due to the fog dependencies.

**Comment by ramereth** [comment]
> FYI: In the past we purposefully did not include these gems due to the fog dependencies.

Is there an inherit problem with the fog deps that I'm not aware of?

**Comment by tyler-ball** [comment]
This is currently failing to build the website, that should get fixed as part of https://github.com/chef/chef-workstation/pull/1037

**Pull request merged**
