### PR TITLE
Fixing expeditor failure - wrong variable capitalization

### PR DESCRIPTION
**Pull request by tyler-ball**
### Description

☝️ 

### Issues Resolved

N/A

### Check List

- [x] PR title is a worthy inclusion in the CHANGELOG
- [ ] You have locally validated the change
- [x] `www/site/content/docs/` has been updated with any relevant changes:
  - * new or changed error messages in 'troubleshooting.md'
  - * new or changed CLI flags in cli-reference.md

### CODE REVIEW

**Comment by tyler-ball** [comment]
@marcparadise https://github.com/chef/chef-workstation/pull/323 fixed the `$version` -> `$VERSION` error on lines 6 and 8 for `.expeditor/announce-release.sh` but did not fix it for lines 10 and 15. This fixes it for lines 10 and 15

**Comment by tyler-ball** [comment]
@marcparadise https://github.com/chef/chef-workstation/pull/323 fixed the `$version` -> `$VERSION` error on lines 6 and 8 for `.expeditor/announce-release.sh` but did not fix it for lines 10 and 15. This fixes it for lines 10 and 15

**Comment by tyler-ball** [comment]
Also double checked `.expeditor/publish-release-notes.sh` and all the bash variables in there have the correct capitalization

**Comment by marcparadise** [comment]
Cool, thanks @tyler-ball

**Pull request merged**
