### PR TITLE
Fix release scripts.

### PR DESCRIPTION
**Pull request by jonsmorrow**
Signed-off-by: Jon Morrow <jmorrow@chef.io>

### Description

☝️ 

### Check List

- [X] PR title is a worthy inclusion in the CHANGELOG
~- [ ] You have locally validated the change~
~- [ ] `www/site/content/docs/` has been updated with any relevant changes:~
  ~- * new or changed error messages in 'troubleshooting.md'~
  ~- * new or changed CLI flags in cli-reference.md~

### CODE REVIEW

**Comment by robbkidd** [comment]
Is this because `${product_key}` wasn't working?

**Comment by jonsmorrow** [comment]
Yeah for some reason the script doesn't find product key.

**Comment by robbkidd** [comment]
My first thought is that `${product_key}` not working in these scripts called by [a workload that claims it has a `product_key`](https://expeditor.chef.io/docs/reference/workloads/#artifact) is what we should fix.

**Comment by schisamo** [comment]
Closing this as a more complete fix is part of https://github.com/chef/chef-workstation/pull/323

**Pull request closed without merging**
