### PR TITLE
Update libxml2 to 2.9.12

### PR DESCRIPTION
**Pull request by tas50**
This resolves multiple CVEs

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by tas50** [comment]
https://buildkite.com/chef/chef-chef-workstation-master-omnibus-adhoc/builds/531#fd57790f-736c-4c69-98bc-b1a43d59b7b4

**Review by vkarve-chef — APPROVED** [review]

**Review by i5pranay93 — APPROVED** [review]

**Review by nikhil2611 — APPROVED** [review]

**Comment by tas50** [comment]
This fails adhocs

**Review by marcparadise — APPROVED** [review]

**Comment by tas50** [comment]
https://buildkite.com/chef/chef-chef-workstation-master-omnibus-adhoc/builds/565#1a4b381d-21bd-4485-8b9f-209e89ca0343

**Comment by tas50** [comment]
This doesn't work

**Pull request closed without merging**
