### PR TITLE
Include `mdl` markdown linter.

### PR DESCRIPTION
**Pull request by jaymzh**
## Description

This closes https://github.com/chef/chef-workstation/issues/541

Currently we can lint ruby (with `rubocop`) but not the `README.md`s.
This includes `mdl` in the omnibus build. It's a lightweight extensible
markdown linter.

Signed-off-by: Phil Dibowitz <phil@ipom.com>

## Related Issue

https://github.com/chef/chef-dk/issues/1601

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:
- [X] I have read the **CONTRIBUTING** document.
- [X] I have run the pre-merge tests locally and they pass.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tyler-ball** [comment]
Tried to `rake update` in here to resolve the gems and I'm getting some conflicts:

```
Bundler could not find compatible versions for gem "mixlib-cli":
  In Gemfile:
    chef-bin (= 15.2.20) was resolved to 15.2.20, which depends on
      chef (= 15.2.20) was resolved to 15.2.20, which depends on
        mixlib-cli (>= 2.1.1, < 3.0)

    mdl was resolved to 0.3.1, which depends on
      mixlib-cli (>= 1.5.0, ~> 1.5)
```

Looks like https://github.com/markdownlint/markdownlint will need to get updated before we can merge this.

**Comment by tyler-ball** [comment]
I know we also had some discussions recently about reducing our included gems to ones that facilitate specific flows. Would you have any issues with `chef gem install mdl` to support the Markdown lint flow @jaymzh?

**Comment by jaymzh** [comment]
@tyler-ball I'd rather not have be munging the gems effectively in  "homedirectory" on every. single. laptop. And in Jenkins. And in the circle-ci checks. and.... so on and so forth.

the dk should include all linters relevant to cookbooks, and this seems pretty well in that category.

**Comment by jaymzh** [comment]
Also, somehow I missed your first comment on this, sorry, must have been on vacation. I can send a PR to MDL, they're super responsive.

**Comment by jaymzh** [comment]
rebased, linked relevant markdownlint issue..

**Comment by tyler-ball** [comment]
Adding https://github.com/markdownlint/markdownlint/pull/265 for tracking. After that gets merged and released we can get the `Gemfile.lock` update added to this PR and get it merged. I don't think it adds many transitive dependencies

**Comment by tyler-ball** [comment]
@jaymzh This is blocked until we can get your mdl PR merged. Any ideas on how to move that forward?

**Comment by jaymzh** [comment]
I reached out to the author in twitter last week, and haven't had a response yet. If I can't get traction soon (it seems a bit like he's abandoned that repo), I will see if I can get a handful of people who are interested in maintaining it and fork it. There's enough contributors that should be doable. But I haven't forgotten. ;)

**Comment by tyler-ball** [comment]
Thanks! If you end up forking that repo, what do you think about getting auto-correct added to that linter?

**Comment by jaymzh** [comment]
I think I'd be stoked at accept such a PR :)

**Comment by jaymzh** [comment]
Just an update... I said twitter, but it was actually email. That was 9/27. I followed up with an email today. If I don't hear back this week I will file an issue suggesting a fork and I will tag everyone who has open PRs to see if they're interested in being co-maintainers. If there's support I'll create markdown-ng org or some such, fork into that, give anyone interested admin, and start merging PRs (assuming they look good, etc.). My goal would be NOT to turn into a full-time maintainer, but to get a group of people who can each at least start letting in PRs and keep the project moving forward. But I wanted to give the current maintainer plenty of opportunity to respond...

**Comment by jaymzh** [comment]
OK the fork has been created. The new PR to track is https://github.com/markdownlint-ng/markdownlint-ng/pull/2

There's a few other cleanups to do and then to release a gem, and then I'll update this PR to reference the `markdown-ng` gem, and then we'll be good to go.

**Comment by jaymzh** [comment]
We got ahold of one of the maintainers of the original... so news is even better. I'm a maintainer now of the original, will be killing the fork, and again, within this week we'll have a new release and I'll update this PR.

**Comment by jaymzh** [comment]
Version 0.6.0 of mdl is out which updates this dependency. You should be set to try again.

**Comment by jaymzh** [comment]
Also I should @tyler-ball so this doesn't get missed in the noise.

**Comment by tyler-ball** [comment]
@jaymzh If https://github.com/jaymzh/chef-workstation/pull/1 looks good, merge that to your branch then we can merge this

**Comment by jaymzh** [comment]
Done!

**Comment by tyler-ball** [comment]
Closing this in favor of https://github.com/chef/chef-workstation/pull/606 since I messed up the rebase in here. Thank you @jaymzh for the PR!

**Pull request closed without merging**
