### PR TITLE
Fix TOC for chef-vault

### PR DESCRIPTION
**Pull request by chuhn**
The levels of the headings in this document are pretty messed up. It has 3 major sections:
1. knive vault
2. Using chef-vault in cookbooks
3. Using chef-vault standalone

Also "Example Commands" should be one level above the specific commands, not in the same level.

## Related Issue

I think the documentation of `knife vault` should be split out into a separate document and references from here.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Review by IanMadd — APPROVED** [review]

**Comment by IanMadd** [comment]
@chuhn can you add your DCO signoff to your commit. 
https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco

**Comment by chuhn** [comment]
> @chuhn can you add your DCO signoff to your commit. https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco

OK, how do I do that technically? Edit the commit and force-push the MR branch?

**Comment by IanMadd** [comment]
> > @chuhn can you add your DCO signoff to your commit. https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco
> 
> OK, how do I do that technically? Edit the commit and force-push the MR branch?

Yeah `git commit --amend -s` and force push should fix it.

**Comment by chuhn** [comment]
OK, DCO done.

**Review by ashiqueps — APPROVED** [review]

**Pull request merged**
