### PR TITLE
Fixing indentation issue on third-party-package pipeline

### PR DESCRIPTION
**Pull request by tyler-ball**
## Description
Error from buildkite:
```
2020-05-14 16:38:51 WARN   POST https://agent.buildkite.com/v3/jobs/b94f1321-bd21-465c-adf8-bee6fe85de54/pipelines: 422 `executor` is not a valid property on the `command` step. Please check the documentation to get a full list of supported properties. (Attempt 1/60 Retrying in 5s)
--
  | 2020-05-14 16:38:51 ERROR  Unrecoverable error, skipping retries
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by tyler-ball** [comment]
@marcparadise So the issue now is that if we use the `anka` builder we get `expeditor/create_pr_for_homebrew.sh: line 91: open_pull_request: command not found`. So we either need to use the `chefes/lita-worker` images and install brew on them, or use the macos builder and manually open our own PR.

**Comment by tyler-ball** [comment]
I vote for using the anka builder (which already has `brew` installed) and just inlining the `open_pull_request` function into our specific script.

**Comment by tyler-ball** [comment]
```
root@d70d02084fac:/# type open_pull_request
open_pull_request is a function
open_pull_request ()
{
    repo=$(git remote get-url origin | sed -rn  's/.+github\.com[\/\:](.*)\.git/\1/p');
    head=$(git rev-parse --abbrev-ref HEAD);
    title=$(git log --oneline --pretty=%s -1);
    base=${1:-"master"};
    if [[ "$head" == "$base" ]]; then
        echo "ERROR: You cannot open a pull request with the same head and base.";
        exit 1;
    fi;
    git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${repo}.git" "$head" --force;
    curl --header "Authorization: token $GITHUB_TOKEN" --data "{\"title\":\"$title\",\"head\":\"$head\",\"base\":\"$base\",\"maintainer_can_modify\":true}" -XPOST "https://api.github.com/repos/$repo/pulls"
}
```

**Comment by marcparadise** [comment]
@tyler-ball running that through now

**Comment by tyler-ball** [comment]
Hey @marcparadise - whats the status on this? I can take this off your plate and get it over the finish line since I know you are busy with the data bag card

**Comment by marcparadise** [comment]
I'd thought you were picking this up earlier in the week. I should have time to resume it this afternoon, but some additional eyes would be good - as of most recent attempt I'm getting an ambiguous error from github; I linked it in channel some time back, but will update this with the latest info today.

**Pull request closed without merging**
