### PR TITLE
Don't exclude dev group in kitchen/berks appbundle

### PR DESCRIPTION
**Pull request by marcparadise**
Excluding 'development' prevents the gems used by
`verify` tests from being identified as dependencies at
package build time, making them unavailable when `verify`
tries to bundle install them.

This change does not cause the development gems to be shipped in
Workstation; it makes them available for `verify`
to install when needed.

Signed-off-by: Marc A. Paradise <marc.paradise@gmail.com>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by marcparadise** [comment]
running this through an adhoc omnibus build to `verify` before merging.

**Comment by tas50** [comment]
I feel like there was a reason for this originally. Not sure what though.

**Comment by marcparadise** [comment]
> I feel like there was a reason for this originally. Not sure what though. 

My misdirected attempts to stop our inclusion of `cucumber` as a shipped gem.

**Comment by tyler-ball** [comment]
@marcparadise Do we still need to merge this PR since you moved the verify functionality out into its own component?

**Comment by tyler-ball** [comment]
Master is building correctly with the kitchen verify tests from https://github.com/chef/chef-workstation/blob/6c8b9603207050c862049ab8177c7c582605eedd/omnibus/verification/verify.rb#L108-L126

Trying to build without excluding these dependencies introduces errors during appbundling from conflicts around cucumber/gherkin/aruba/etc.

Going to close this for now - lets re-open it if I am misunderstanding something!

**Pull request closed without merging**
